// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Todos$RescriptReactTodos from "./Todos.bs.js";

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(Todos$RescriptReactTodos.make, {}));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
