// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var githubUsersEndpoint = "https://api.github.com/users";

function GithubUsers(Props) {
  var match = React.useState(function () {
        return /* Idle */0;
      });
  var setStatus = match[1];
  var match$1 = React.useState(function () {
        return [];
      });
  var setUsers = match$1[1];
  var transformUser = function (user) {
    return {
            id: user.id,
            username: user.login,
            avatar_url: user.avatar_url,
            url: user.url
          };
  };
  React.useEffect((function () {
          Curry._1(setStatus, (function (param) {
                  return /* Pending */1;
                }));
          Axios.get(githubUsersEndpoint).then(function (response) {
                  var transformedUsers = Belt_Array.map(response.data, transformUser);
                  Curry._1(setStatus, (function (param) {
                          return /* Resolved */2;
                        }));
                  Curry._1(setUsers, (function (param) {
                          return transformedUsers;
                        }));
                  return Promise.resolve(undefined);
                }).catch(function (error) {
                return Promise.resolve((console.log(error), undefined));
              });
          
        }), []);
  var userItemEl = Belt_Array.map(match$1[0], (function (user) {
          return React.createElement("div", {
                      key: String(user.id)
                    }, React.createElement("p", undefined, user.username));
        }));
  var tmp;
  switch (match[0]) {
    case /* Idle */0 :
        tmp = React.createElement(React.Fragment, undefined);
        break;
    case /* Pending */1 :
        tmp = React.createElement("p", undefined, "Loading...");
        break;
    case /* Resolved */2 :
        tmp = React.createElement("div", undefined, userItemEl);
        break;
    case /* Rejected */3 :
        tmp = React.createElement("p", undefined, "Something went wrong");
        break;
    
  }
  return React.createElement(React.Fragment, undefined, React.createElement("h2", undefined, "GitHub users"), tmp);
}

var make = GithubUsers;

export {
  githubUsersEndpoint ,
  make ,
  
}
/* axios Not a pure module */
