// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as TodoItem$RescriptReactTodos from "./TodoItem.bs.js";

var todos = [
  {
    id: "1",
    body: "Go to school",
    completed: false
  },
  {
    id: "2",
    body: "Go to the gym",
    completed: true
  }
];

function Todos(Props) {
  var match = React.useState(function () {
        return todos;
      });
  var setTodos = match[1];
  var todos$1 = match[0];
  var todoList = Belt_Array.map(todos$1, (function (todo) {
          return React.createElement(TodoItem$RescriptReactTodos.make, {
                      body: todo.body,
                      completed: todo.completed,
                      onChange: (function (e) {
                          var id = todo.id;
                          var checked = e.target.checked;
                          var updatedTodos = Belt_Array.map(todos$1, (function (todo) {
                                  if (todo.id !== id) {
                                    return todo;
                                  } else {
                                    return {
                                            id: todo.id,
                                            body: todo.body,
                                            completed: checked
                                          };
                                  }
                                }));
                          return Curry._1(setTodos, (function (param) {
                                        return updatedTodos;
                                      }));
                        }),
                      key: todo.id
                    });
        }));
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Todos"), React.createElement("div", {
                  className: "todo-list"
                }, todoList));
}

var make = Todos;

export {
  todos ,
  make ,
  
}
/* react Not a pure module */
