// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TodoItem(Props) {
  var body = Props.body;
  var completed = Props.completed;
  var onChange = Props.onChange;
  return React.createElement("div", {
              className: "todo-item"
            }, React.createElement("p", undefined, body), React.createElement("input", {
                  checked: completed,
                  type: "checkbox",
                  onChange: onChange
                }));
}

var make = TodoItem;

export {
  make ,
  
}
/* react Not a pure module */
