// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TodoItem(Props) {
  var body = Props.body;
  var completed = Props.completed;
  return React.createElement("div", undefined, React.createElement("p", undefined, body), React.createElement("input", {
                  checked: completed,
                  type: "checkbox"
                }));
}

var make = TodoItem;

export {
  make ,
  
}
/* react Not a pure module */
