// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as TodoItem$RescriptReactTodos from "./TodoItem.bs.js";

var todos = [
  {
    id: "1",
    body: "Go to school",
    completed: false
  },
  {
    id: "2",
    body: "Go to the gym",
    completed: true
  }
];

function Todos(Props) {
  var todoList = Belt_Array.map(todos, (function (todo) {
          return React.createElement(TodoItem$RescriptReactTodos.make, {
                      body: todo.body,
                      completed: todo.completed,
                      key: todo.id
                    });
        }));
  return React.createElement("div", {
              className: "todos_list"
            }, React.createElement("h1", undefined, "Todos"), todoList);
}

var make = Todos;

export {
  todos ,
  make ,
  
}
/* react Not a pure module */
