// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as TodoItem$RescriptReactTodos from "./TodoItem.bs.js";

var fixedTodos = [
  {
    id: "1",
    body: "Go to school",
    completed: false
  },
  {
    id: "2",
    body: "Go to the gym",
    completed: true
  }
];

function Todos(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setTodos = match[1];
  var todos = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setLoading = match$1[1];
  var fetchData = function (param) {
    return Promise.resolve(fixedTodos).then(function (res) {
                return Promise.resolve(res);
              });
  };
  React.useEffect((function () {
          Curry._1(setLoading, (function (param) {
                  return true;
                }));
          fetchData(undefined).then(function (res) {
                Curry._1(setTodos, (function (param) {
                        return res;
                      }));
                Curry._1(setLoading, (function (param) {
                        return false;
                      }));
                return Promise.resolve(res);
              });
          
        }), []);
  var todoList = Belt_Array.map(todos, (function (todo) {
          return React.createElement(TodoItem$RescriptReactTodos.make, {
                      body: todo.body,
                      completed: todo.completed,
                      onChange: (function (e) {
                          var id = todo.id;
                          var checked = e.target.checked;
                          var updatedTodos = Belt_Array.map(todos, (function (todo) {
                                  if (todo.id !== id) {
                                    return todo;
                                  } else {
                                    return {
                                            id: todo.id,
                                            body: todo.body,
                                            completed: checked
                                          };
                                  }
                                }));
                          return Curry._1(setTodos, (function (param) {
                                        return updatedTodos;
                                      }));
                        }),
                      key: todo.id
                    });
        }));
  var loadingEl = React.createElement("p", undefined, "Loading...");
  var todoEl = React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Todos"), React.createElement("div", {
            className: "todo-list"
          }, todoList));
  if (match$1[0]) {
    return loadingEl;
  } else {
    return todoEl;
  }
}

var make = Todos;

export {
  fixedTodos ,
  make ,
  
}
/* react Not a pure module */
